nearform/graphql-hooks

.editorconfig, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
=> Adds bundle size to readme and EditorConfig, Code of Conduct, Contributing docs.

src/index.js
=> Preset useCache=true for useManualQuery

README.md
https://bundlephobia.com/result?p=graphql-hooks@3.1.0
=> update README bundle size to reflect minor increase

README.md
Query simplification that was missed in #44
See https://github.com/nearform/graphql-hooks/pull/44#discussion_r259779125
=> Simplify pagination example query

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/Bug_Report.md, .github/ISSUE_TEMPLATE/Feature_Request.md, .github/PULL_REQUEST_TEMPLATE.md
Closes #20 
Adds the following GitHub templates
- General issue template
- Bug report issue template
- Feature request issue template
- Pull request template
=> Issue, bug, feature & PR templates

.eslintrc.js, .prettierrc, CONTRIBUTING.md, package.json, src/GraphQLClient.js, test/integration/useQuery.test.js, test/unit/GraphQLClient.test.js, test/unit/useClientRequest.test.js, test/unit/useQuery.test.js
- adds `eslint`
- switches to the recommended `lint-staged` to integrate with `prettier`
- pulls in `eslint-plugin-react-hook` 👍 
- formats files that needed formatting
- disables `no-console` for logging in the `GraphQLClient` file
#64
=> feat: integrate eslint-plugin-react-hooks

.circleci/config.yml, src/useClientRequest.js, src/useQuery.js
Runs ESlint on circleCI and fixes the existing eslint warnings. Used the junit format so that circleci can read the output. See a run here with warnings: https://circleci.com/gh/nearform/graphql-hooks/219
=> Run ESLint on CircleCI

src/GraphQLClient.js
=> Missing console.groupEnd()

packages/graphql-hooks/package.json
The paths weren't relative, it makes them so.
#98
=> Fix postpublish script for graphql-hooks

.prettierrc, README.md, babel.config.js, jest.config.js, packages/graphql-hooks-memcache/README.md, packages/graphql-hooks-memcache/index.js, packages/graphql-hooks-ssr/README.md, packages/graphql-hooks-ssr/index.js, packages/graphql-hooks/rollup.config.js, packages/graphql-hooks/src/.babelrc.js, packages/graphql-hooks/src/ClientContext.js, packages/graphql-hooks/src/GraphQLClient.js, packages/graphql-hooks/src/index.js, packages/graphql-hooks/src/useClientRequest.js, packages/graphql-hooks/src/useQuery.js, packages/graphql-hooks/test/integration/useQuery.test.js, packages/graphql-hooks/test/setup.js, packages/graphql-hooks/test/setupAfterEnv.js, packages/graphql-hooks/test/unit/GraphQLClient.test.js, packages/graphql-hooks/test/unit/useClientRequest.test.js, packages/graphql-hooks/test/unit/useManualQuery.test.js, packages/graphql-hooks/test/unit/useMutation.test.js, packages/graphql-hooks/test/unit/useQuery.test.js
Switches prettier config to set `semi: false`. 
I've done this after speaking with @bmullan91 about it. I noticed whilst moving the other packages into this repo that they were both `semi: false`.
=> Remove semi colons

README.md
=> docs: remove stray ;

.github/ISSUE_TEMPLATE/Bug_Report.md, .github/ISSUE_TEMPLATE/Feature_Request.md
Removes checklist from issue template so that it doesn't show up on the project board.
=> Update issue templates to remove checklist

CONTRIBUTING.md, lerna.json, packages/graphql-hooks-memcache/CHANGELOG.md, packages/graphql-hooks-ssr/CHANGELOG.md, packages/graphql-hooks/CHANGELOG.md
- Adds [conventional commits Lerna configuration](https://github.com/lerna/lerna/blob/030de9d6285f2b364ed1460b9534bc2190acdf7a/commands/version/README.md#--conventional-commits)
- Adds [GitHub release Lerna configuration](https://github.com/lerna/lerna/blob/030de9d6285f2b364ed1460b9534bc2190acdf7a/commands/version/README.md#--github-release)
- Updates CONTRIBUTING.md 
Resolves #48
=> Conventional commits

.gitignore, packages/graphql-hooks-memcache/package.json, packages/graphql-hooks-ssr/package.json, packages/graphql-hooks/package.json
Remove unnecessary `postpublish` scripts
=> chore: remove unnecessary postpublish scripts

README.md, packages/graphql-hooks-memcache/README.md
A few small README changes after running them through https://www.grammarly.com/
=> docs: README grammar fixes

README.md
Adds a spectrum badge to the README.md
#157
=> chore: Add Spectrum Badge to README.md

examples/create-react-app/package.json, examples/fastify-ssr/package.json
Updates version of React and react-dom in the example packages to match that of the lib. Which in turn should fix the CI.
=> chore(deps): Update react version in example apps

.circleci/config.yml
=> fix: Revert #264 - queuing acceptance tests in circleci

README.md
Add an example to README.md how to use custom fetch (axios) with interceptors. Handy for handling JWT token. 
https://github.com/nearform/graphql-hooks/issues/308
=> docs: add example of using axios as custom fetch with interceptors

.circleci/config.yml, package.json, packages/graphql-hooks-memcache/package.json, packages/graphql-hooks-ssr/package.json, packages/graphql-hooks/package.json, packages/graphql-hooks/src/useClientRequest.js, packages/graphql-hooks/src/useQuery.js, packages/graphql-hooks/test/integration/useQuery.test.js
- fixes #371 
- Updates `clean` command to also clear out build folders - useful for debugging
- Updates `postinstall` to run the build command in each package - required for testing
#371
=> fix: Server-side rendering

README.md, package.json, packages/graphql-hooks-memcache/.size-snapshot.json, packages/graphql-hooks-memcache/package.json, packages/graphql-hooks/.size-snapshot.json, packages/graphql-hooks/package.json
Fixes issue when trying to run `npm run build` in each package - For the past few releases I've had to dance around this manually.
See related issue RE cli deps + lerna: https://github.com/lerna/lerna/issues/470
N/A
=> fix: publishing issues

examples/create-react-app/package.json, examples/fastify-ssr/package.json, package.json, packages/graphql-hooks-ssr/package.json, packages/graphql-hooks/package.json, packages/graphql-hooks/test/unit/GraphQLClient.test.js, packages/graphql-hooks/test/unit/useClientRequest.test.js
Cleans up all the warnings/errors displayed when running the tests.
#68
=> fix: Update tests

README.md
Adds authentication description and example to readme.md file
[#26 ](https://github.com/nearform/graphql-hooks/issues/26)
=> Docs: Authentication Guide

packages/graphql-hooks-memcache/package.json
Fixes an IE11 issue due to usage of arrow functions in `fnv1a` module
#476
=> Upgrade to latest version of fnv1a

.netlify/functions/deploy-succeeded.js, README.md, examples/subscription/README.md, examples/subscription/src/server/index.js, package.json, packages/graphql-hooks/index.d.ts, packages/graphql-hooks/test/unit/GraphQLClient.test.js
It updates prettier to v2 and includes the rules that keep the minimal changes in the base code.
The [renovate PR](https://github.com/nearform/graphql-hooks/pull/479) is safe to remove, as this one will replace it.
=> chore: updating prettier

packages/graphql-hooks/index.d.ts
Fixes 491 
https://github.com/nearform/graphql-hooks/issues/491
=> fix: Fixes GraphqlClient type in index.d.ts

README.md
Documentation from https://github.com/nearform/graphql-hooks/pull/501 with minor typo changes
=> chore: updated documentation

renovate.json
Update renovate bot settings to auto merge minor versions and patches.
=> Auto merge minor and patch deps

packages/graphql-hooks-ssr/index.d.ts
=> fix: missing type promise of async function

renovate.json
Fix Renovate configuration (my bad) and create master issue to keep track of pending updates.
=> fix: renovate configuration

renovate.json
Preserve Renovate semver ranges to avoid pinning.
=> chore: renovate preserve semver ranges to avoid pinning

.github/workflows/acceptance-tests.yml, .github/workflows/ci.yml, examples/create-react-app/Dockerfile
Upgrades Node 12 to 14.
Closes Closes https://github.com/nearform/graphql-hooks/issues/613
=> chore: use node 14 LTS

packages/graphql-hooks/src/GraphQLClient.js, packages/graphql-hooks/src/canUseDOM.js, packages/graphql-hooks/test/unit/GraphQLClient.test.js
Don't throw an error if fetch is not polyfilled and ssrMode is set to false.
Fixes #620
=> Don't require fetch polyfill if ssrMode is false

jest.config.js, packages/graphql-hooks/test/unit/GraphQLClient.test.js
=> fix: change testEnvironment to jsdom

.github/workflows/create-react-app-server.yml, examples/create-react-app/package.json
Fixes the deployment of the graphql mock server used by the example react application
=> chore: fix graphql mock server deployment

.github/workflows/stale.yml
Adds a workflow to run the https://github.com/actions/stale github action
=> feat: stale

.github/workflows/create-react-app-server.yml
Supersedes https://github.com/nearform/graphql-hooks/pull/722
=> chore(deps): Bump google-github-actions/setup-gcloud from 0.2.1 to 0.3

.github/workflows/ci.yml, examples/typescript/package.json
fixes https://github.com/nearform/graphql-hooks/issues/734
=> chore: fixes the build job on the ci workflow

packages/graphql-hooks-ssr/README.md
=> docs: Add missing comma to code snippet in README

.github/workflows/check-linked-issues.yml
=> fix: updating pull request event

.github/workflows/notify-twitter.yml
Adds a new workflow to send a tweet to [@NearFormOSS](https://twitter.com/NearFormOSS) upon successful release.
Closes #801
=> feat: add notify-twitter workflow

.github/workflows/ci.yml, examples/typescript/package.json, packages/graphql-hooks-ssr/package.json, packages/graphql-hooks/package.json
=> chore: include react 18 as a supported peerDependency

packages/graphql-hooks/test/unit/GraphQLClient.test.js
- Adds test of fetch binding
resolves #821
=> test: add fetch bind test

babel.config.js, jest.config.js, package.json, packages/graphql-hooks-ssr/index.test.tsx
Closes #920 
This should also close #923
=> fix: removed ts jest

packages/graphql-hooks/src/types/common-types.ts, packages/graphql-hooks/src/useClientRequest.ts, packages/graphql-hooks/test-jsdom/unit/useMutation.test.tsx
=> fix: onSuccess typings and called when there is an error

packages/graphql-hooks/src/useClientRequest.ts, packages/graphql-hooks/test-jsdom/unit/useClientRequest.test.tsx
=> fix: Event Listener memory leak

README.md
Add a new documentation section to call out the ability to provide typescript type information to client methods. 
Closes #1128
=> chore: add TS section to documentation

examples/create-react-app/package.json, examples/fastify-ssr/package.json, examples/full-ws-transport/package.json, examples/persisted-queries/client/package.json, examples/subscription/package.json, examples/typescript/package.json
- fix version numbers for all example packages. 
Resolves #1154
=> chore: fix versions of all example packages

README.md, packages/graphql-hooks/src/middlewares/README.md
Navigating internal links to existing path and extension.
=> docs(README): recent example links

examples/create-react-app/test/setup.js, jest.config.js, packages/graphql-hooks/src/GraphQLClient.ts, packages/graphql-hooks/src/LocalGraphQLClient.ts, packages/graphql-hooks/test-jsdom/unit/LocalGraphQLClient.test.tsx
Let  `LocalGraphQLClient` to handle `middleware`and `responseReducer`
resolve #1196
=> fix(LocalGraphQLClient): handle middleware and responseReducer

README.md
Updated Nearform Banner in Readme.md file
=> update banner link

examples/create-react-app/README.md
Update links for Create React App example
=> docs: fix example links
