.circleci/config.yml, .gitignore, README.md, babel.config.js, package-lock.json, package.json, test/unit/createClient.test.js, test/unit/useClientRequest.test.js, test/unit/useQuery.test.js, test/useQuery.test.js
Closes #3 
Set up the foundation for a test suite including the following
=> Set up test suite

package-lock.json, package.json, src/GraphQLClient.js, test/setup.js, test/unit/GraphQLClient.test.js
Part of #9 
Add test coverage for `GraphQLClient`
``` PASS  test/unit/GraphQLClient.test.js
GraphQLClient
when instantiated
✓ throws if no url provided (10ms)
✓ throws if fetch is not a function (1ms)
✓ throws if fetch is not present or polyfilled (1ms)
✓ assigns config.cache to an instance property
✓ assigns config.headers to an instance property
✓ assigns config.ssrMode to an instance property
✓ assigns config.url to an instance property (1ms)
✓ assigns config.fetch to an instance property
✓ assigns config.fetchOptions to an instance property
✓ assigns config.logErrors to an instance property (1ms)
✓ assigns config.onError to an instance property
setHeader
✓ sets the key to the value (1ms)
setHeaders
✓ replaces all headers
logErrorResult
✓ calls onError if present (3ms)
✓ logs a …
```
=> Unit tests for GraphQLClient

package-lock.json, package.json
This was removed in #5 - but wasn't removed from the list of `dependencies`
=> Remove graphql-request from dependencies

test/unit/useQuery.test.js
Part of #9 
Add test coverage for `useQuery`
```
PASS  test/unit/useQuery.test.js
useQuery
✓ calls useClientRequest with query (22ms)
✓ calls useClientRequest with options (2ms)
✓ returns initial state from useClientRequest & refetch (2ms)
✓ bypasses cache when refetch is called (1ms)
✓ sends the query on mount if no data & no error (2ms)
✓ does not send the same query on mount if data is already present (2ms)
✓ does not send the query on mount if there is an error (1ms)
✓ adds query to ssrPromises when in ssrMode if no data & no error (3ms)
✓ does not add query to ssrPromises when in ssrMode if there is already data (1ms)
✓ does not add query to ssrPromises when in ssrMode if there is an error (1ms)
✓ does not add query to ssrPromises when in ssrMode if ssr is overridden in options (2ms) …
```
=> Unit tests for useQuery

test/unit/useClientRequest.test.js
Part of #9 
Adds unit tests for `useClientRequest`
Note: can't currently test `fetchData`, [see explanation here](https://github.com/nearform/graphql-hooks/blob/9a09e6ca154a03f44855c4684d51ad96988ecf4b/test/unit/useClientRequest.test.js#L76-L94). Raised an issue of this #31.
```
PASS  test/unit/useClientRequest.test.js
useClientRequest
✓ returns a fetch function & state (21ms)
initial state
✓ includes the cached response if present (2ms)
✓ skips the cache if skipCache is passed in (2ms)
✓ skips the cache if a cache is not configured (2ms)
fetchData
○ skipped 1 test
```
=> unit tests for useClientRequest

test/unit/useClientRequest.test.js
Implements the tests that were left out of #30 
Resolves #31 
```
fetchData
✓ calls request with options & updates the state with the result (10ms)
✓ calls request with revised options (2ms)
✓ skips the request & returns the cached data if it exists (2ms)
✓ skips the cache if skipCache is passed in (2ms)
✓ skips the cache if skipCache is there is no cache (2ms)
✓ sets the result from the request in the cache (2ms)
```
The following warning will display in the console for each test until https://github.com/facebook/react/issues/14769 has been resolved. This is because `fetchData` updates the state & should be wrapped inside an `act`, however `act` does not yet support `async/await` & `fetchData` is an async function.
```
console.error node_modules/react-dom/cjs/react-dom.development.js:506 …
```
=> Add useClientRequest fetchData tests with warnings

test/unit/useManualQuery.test.js, test/unit/useQuery.test.js
Part of #9 
Adds a test for `useManualQuery` which is just a proxy to `useClientRequest` with `useCache=true`
```
PASS  test/unit/useManualQuery.test.js
useManualQuery
✓ calls useClientRequest with useCache set to true & options (5ms)
```
=> Unit tests for useManualQuery

test/unit/useMutation.test.js
Part of #9 
Adds a test for `useMutation` which is just a proxy to `useClientRequest`
```
PASS  test/unit/useMutation.test.js
useMutation
✓ calls useClientRequest with options (5ms)
```
=> Unit tests for useMutation

src/useQuery.js, test/unit/useQuery.test.js
See #35 
The following tests are failing because there should be a second request that currently isn't being sent
```
✕ sends the query again if the variables change, even if there was previously data (3ms)
✕ sends the query again if the variables change, even if there was previously an error (3ms)
✕ sends the query again if the query changes, even if there was previously data (2ms)
✕ sends the query again if the query changes, even if there was previously an error (2ms)
```
Remove the `state.data` & `state.error` check inside the `useQuery` effect. It already has conditional checks to make sure it only fires if `query` or `opts.variables` have changed. 
```
✓ sends the query again if the variables change, even if there was previously data (3ms)
✓ sends the query again if the variables …
```
=> Trigger another request if the variables or query change

src/index.js, src/useClientRequest.js, test/unit/useClientRequest.test.js, test/unit/useMutation.test.js
This makes sure that `loading` is set to false when `useMutation` is called. It causes issues having `loading` default to true for a mutation because it doesn't actually send the request until the consumer calls the returned method. 
This is probably considered a breaking change? @bmullan91 / @jackdclark 
Another small thing in this PR is an additional check to avoid making a new state object if we don't need to, this means react won't try to render wastefully.
=> Fix initial loading state with useMutation and add optmization

README.md, src/useClientRequest.js, src/useQuery.js, test/unit/useClientRequest.test.js, test/unit/useQuery.test.js
Closes: #41, closes #42, and closes #29 
~Provides a `fetchMore` function that will send the same query with the provided options merged into the original options, meaning the consumer doesn't have to manually maintain the state.~ Removed this as the same can be achieved with `refetch` now that it accepts `options`.
`useQuery` accepts an `updateData` function as part of the `options` object that enables control of how the previous & new results are merged, this function can be overridden if necessary when calling `refetch` as well.
```jsx
// use options.updateResult to append the new page of posts to our current list of posts
const updateData = (prevData, prevData) => ({
...data,
allPosts: [...prevData.allPosts, ...data.allPosts]
});
export default function PostList() {
// set a default …
```
=> Pagination

package-lock.json, package.json, test/unit/useClientRequest.test.js, test/unit/useQuery.test.js
Closes #51
[react-testing-library](https://github.com/kentcdodds/react-testing-library) moved the `testHook` util to a separate package in [#307](https://github.com/kentcdodds/react-testing-library/pull/307) to discourage unit testing component implementation details. `graphql-hooks` is a library of custom hooks that aren't directly tied to components, therefore it makes sense to migrate to this package to use this util, given that we aren't using any other features from `react-testing-library`.
=> react-testing-library -> react-hooks-testing-library

package-lock.json, package.json, src/useClientRequest.js, src/useQuery.js, test/integration/useQuery.test.js, test/unit/useClientRequest.test.js, test/unit/useQuery.test.js
Fixes bugs (listed below) and also introduces integration tests.
- Fixes #60, #37
=> Integration tests & bug fixes

.github/ISSUE_TEMPLATE/Bug_Report.md, .github/ISSUE_TEMPLATE/Feature_Request.md
Automatically adds bug & feature labels when raising an issue via the Bug Report or Feature Request issue templates
See https://help.github.com/en/articles/manually-creating-a-single-issue-template-for-your-repository
=> Add bug & feature labels to issue templates

CONTRIBUTING.md, package.json
- Removes CLI tool for `all-contributors`
- Using the CLI tool as opposed to bot usage yielded inconsistencies. The CLI generated markup whilst the bot generated markdown.
=> feat: remove all-contributors cli

src/useClientRequest.js, test/unit/useClientRequest.test.js
After updating the next.js example with the latest release we noticed that all our data would disappear when fetching more results. The way we recommend to do that is by updating the variables passed into `useQuery` and supplying an `updateData` method, which is responsible for merging the previous and new results. 
We previously merged a fix (#61) that resets state if variables or query changes in `useClientRequest`. The fix in this is to only reset the state if `updateData` is not set. This means that `state.data` is always populated after the initial request in this scenario.
=> fix: Preserve state if updateData is passed to useClientRequest.

lerna.json
Prevents `package-lock.json` files being generated in the `packages/` directory.
#65
=> Stop lerna generating package lock files in packages

CONTRIBUTING.md, packages/graphql-hooks-memcache/package.json, packages/graphql-hooks-ssr/package.json, packages/graphql-hooks/package.json
- Ensures the readme appears on npm for `graphql-hooks`
- Copies LICENSE file to packages when publishing
- Updates CONTRIBUTING.md with `NPM_CONFIG_OTP` var
=> Copy README to graphql-hooks on publish

CONTRIBUTING.md, lerna.json
Removes Lerna's github release config as it doesn't seem to work well in local testing. Maybe something we can come back to.
=> chore: don't use lerna github releases

config/rollup.config.js, package.json, packages/graphql-hooks-memcache/.size-snapshot.json, packages/graphql-hooks-memcache/package.json, packages/graphql-hooks-memcache/rollup.config.js, packages/graphql-hooks-memcache/src/index.js, packages/graphql-hooks/.size-snapshot.json, packages/graphql-hooks/package.json
- Creates a shared rollup config at the root
- Moves rollup & related dependencies to root
- Adds a rollup config, build & prepublish steps for `graphql-hooks-memcache`
Closes #95
=> feat: cjs, es & umd bundles for graphql-hooks-memcache

packages/graphql-hooks-ssr/index.test.js
Adds a small test for getInitialState in the graphql-hooks-ssr package.
closes #94
=> test: Add test for getInitialState in graphql-hooks-ssr

packages/graphql-hooks-memcache/test/index.test.js
Adds a test for the memcache package.
closes #93
=> test: Add test for graphql-hooks-memcache

README.md, packages/graphql-hooks-ssr/README.md, packages/graphql-hooks-ssr/index.js, packages/graphql-hooks-ssr/index.test.js, packages/graphql-hooks/src/GraphQLClient.js, packages/graphql-hooks/test/unit/GraphQLClient.test.js
- Makes `graphql-hooks-ssr` `getInitialState` throw if no cache is present in the client
- Makes `GraphQLClient` throw if `ssrMode` is true & no cache is provided
- Updates docs to reflect that `client.cache` is required in SSR mode
- Adds regression tests
Fixes #116
=> fix: throw an error if client.cache isn't provided in ssrMode

packages/graphql-hooks/src/index.js, packages/graphql-hooks/src/useClientRequest.js, packages/graphql-hooks/test/unit/useClientRequest.test.js, packages/graphql-hooks/test/unit/useManualQuery.test.js
Calling `useManualQuery` currently returns a state with `loading` set to _true_, despite the request function not having been called.  This PR updates the initial state for manual queries to default to _false_.
Resolves https://github.com/nearform/graphql-hooks/issues/133.
- My implementation simply adds another option field `isManual` to identify the type of request being made, which is quite similar to the `isMutation` field in terms of usage. An alternative (but potentially more restrictive) approach would be to replace the two options with something to indicate the request will not immediately get called, e.g. `isDeferred`.  Please let me know if such an approach would be preferred.
=> Fix default loading stage for useManualQuery

README.md, packages/graphql-hooks-ssr/README.md
Provides a complete guide on how to migrate from `apollo` ➡️`graphql-hooks`. Rendered output: https://github.com/nearform/graphql-hooks/blob/70c9242f7817188611d31ba539f1bda41df23725/README.md
Fixes #28
=> chore(docs): Migrating from Apollo Guide

.circleci/config.yml, .eslintrc.js, .netlify/functions/deploy-succeeded.js, CONTRIBUTING.md, README.md, examples/create-react-app/package.json, examples/create-react-app/src/index.js, package.json, test/acceptance/basic.acceptance.test.js, test/acceptance/globals.js
Adds a simple acceptance test that ensures the create-react-app example renders a list of posts.
The majority of this PR is setting up the CI. The process is as follows:
- PR is opened
- CircleCI runs normal "test" build
- Netlify deploys preview of create-react-app example.
- Netlify sends a request on `deploy-succeeded` to CircleCI telling it to run the job `acceptance-tests` on correct branch, along with a `ACCEPTANCE_URL` parameter that points to the Netlify preview.
- CircleCI runs `npm run test:acceptance:ci`, which uses testcafe and browserstack.
This process makes use Netlify functions, which handily you can trigger from certain Netlify events. We make use of the `deploy-succeeded` event by naming our function file `deploy-succeeded.js`, easy. 
closes #119
=> test: Acceptance tests

packages/graphql-hooks-memcache/index.d.ts, packages/graphql-hooks-memcache/package.json
Adds a [https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) for `graphql-hooks-memcache` that will be published to npm, so that the package works well with TypeScript.
#91
=> feat: add a TypeScript declaration file for graphql-hooks-memcache

README.md
- Make bundlephobia badge link to https://bundlephobia.com/result?p=graphql-hooks
- Update unzipped size in README
=> docs(README): update bundlephobia badge to link to site & update size

packages/graphql-hooks-ssr/index.d.ts, packages/graphql-hooks-ssr/package.json
Adds a [https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) for `graphql-hooks-ssr` that will be published to npm, so that the package works well with TypeScript.
You can test this out locally by rebasing on #136, rebuilding everything & looking at `examples/typescript` in your IDE.
Resolves #91
=> feat: add a TypeScript declaration file for graphql-hooks-ssr

packages/graphql-hooks/index.d.ts
The following throws without the propper type declarations when using `graphql-hooks` with typescript:
```
ERROR in [at-loader] ./node_modules/graphql-hooks/index.d.ts:44:25
TS7031: Binding element 'Operation' implicitly has an 'any' type.
ERROR in [at-loader] ./node_modules/graphql-hooks/index.d.ts:44:44
TS7031: Binding element 'Result' implicitly has an 'any' type.
```
Fixes type errors when using typescript.
=> Fix type declarations for logErrorResult & onError

README.md, packages/graphql-hooks/src/useClientRequest.js, packages/graphql-hooks/test/unit/useClientRequest.test.js
Warns the user if they are passing in a query that is not a string. A common case might be if users use the `gql` template literal from graphql-tag on their queries.
#197
=> String warning

packages/graphql-hooks/package.json, packages/graphql-hooks/test/integration/useQuery.test.js, packages/graphql-hooks/test/setupAfterEnv.js
react-testing-library has been deprecated and replaced by the new version of @testing-library/react.
N/A
=> chore(deps): replace react-testing-library with @testing-library/react

.circleci/config.yml
The free version of browserstack.com is giving a limited number of free runners. If we have multiple PRs pending from renovatebot we initiate acceptance tests runners at the same time. That causes the job to fail since we run out of the browserstack runners.
With CircleCI queue orb we can pause the step and wait for other jobs to complete. As a result, we should not have acceptance-tests running concurrently.
The downside of this is that the execution time for every job might be very different.
N/A
=> chore(CI): adds queuing step in acceptance-tests job

renovate.json
Renovate bot is not checking `example/**/package.json` projects since they are ignored after inheriting `ignorePaths` list that includes `examples/**`. I did experiment having an explicit packagePaths property for examples folders but nothing seemed to work. The only option was to set `ignorePaths` to the empty list. I added `includePaths` to make it more efficient to scan only defined folders.
- https://github.com/nearform/graphql-hooks/issues/178
=> chore: updates renovate config to include examples dir

README.md, packages/graphql-hooks/index.d.ts, packages/graphql-hooks/src/GraphQLClient.js, packages/graphql-hooks/test/unit/GraphQLClient.test.js
Allows to remove a previously set header from `GraphQLClient`.
Closes #247.
=> Allow to remove header

packages/graphql-hooks/package.json, packages/graphql-hooks/test/unit/useClientRequest.test.js, packages/graphql-hooks/test/unit/useQuery.test.js
`react-hooks-testing-library` advised to move to `@testing-library/react-hooks`, so that's what this PR does.
=> chore: move to use @testing-library/react-hooks

packages/graphql-hooks/index.d.ts
Adds an opt-in generic type for variables in a GraphQL operation.
**Before**
```tsx
interface QueryData {
projectName: string;
}
useQuery<QueryData>(PROJECT_QUERY, {
variables: {
teamId: 'someString'
},
});
```
**After**
```tsx
interface QueryData {
projectName: string;
}
interface QueryVariables {
teamId: string;
}
useQuery<QueryData, QueryVariables>(PROJECT_QUERY, {
// options.variables is now of type QueryVariables
variables: {
teamId: 'someString'
},
});
```
=> Add support for generic Variables TS type (#348)

packages/graphql-hooks-memcache/.size-snapshot.json, packages/graphql-hooks-memcache/package.json, packages/graphql-hooks-memcache/src/index.js, packages/graphql-hooks/.size-snapshot.json
Tries to fix webpack import issue when used within next.js applications.
Compared to #369, this PR attempts to keep the current LRU package.
This PR changes the import for tiny-lru to use ES5 code from tiny-lru, because tiny-lru does not expose es6 correctly.
Note: I plan to fix the tiny-lru es6 export issue, at which point we should upgrade this import to use es6 instead.
#366 
#369 (PR)
=> fix #366 - fix the import issues for webpack

.circleci/config.yml, package.json
Disables `acceptance-tests` circleci job, it's been a frequent source of failing builds ❌mainly due to browserstack failing when running more than 5 parallel tests, we need to cough up 💸 to get more.
=> fix: disable acceptance-tests ciricleci job

.circleci/config.yml, CONTRIBUTING.md, README.md, package.json
- Removes browserstack from the acceptance tests, it's been source of pain for a while for failed builds.
- Re-enables the acceptance tests, which will run the tests on testcafe 
N/A
=> fix: re-enable acceptance tests, remove browserstack usage

packages/graphql-hooks/src/useClientRequest.js, packages/graphql-hooks/test/integration/useQuery.test.js, packages/graphql-hooks/test/unit/useClientRequest.test.js
Updates the dispatch call for `CACHE_HIT` which sets `resetState: boolean` if the state.cacheKey is different from the current cacheKey.
#387
=> Fix caching issue when options.updateData is passed

packages/graphql-hooks/index.d.ts
It is a small change, but without it, I would always need to cast the data to any:
```
const result = await client.request({query: QUERY}, {});
(result.data as any).data.something
```
If this merged, we can simply do this:
```
const result = await client.request<{data: DataInterface}>({query: QUERY}, {});
result.data.data.something
```
By the way, I don't think the default type of `Result.data` should be`object` type. More appropriate type is `any` or even `unknown`. Although I think `any` is better.
- [ X ] I have checked the [contributing document](../blob/master/CONTRIBUTING.md)
- [ X ] I have added or updated any relevant documentation: Not Applicable
- [ X ] I have added or updated any relevant tests: Not Applicable
=> Use generics in GraphQLClient.request method

packages/graphql-hooks/src/useQuery.js, packages/graphql-hooks/test/integration/useQuery.test.js
Adds a check before calling the `queryReq` fn during SSR, if the `skipCache` option is `false`, we ignore.
#396
=> fix: SSR infinite loop when skipCache=true

packages/graphql-hooks/index.d.ts
- Passes along a `Variables` generic type to `FetchData`. This was lost along the way when doing a `useMutation`.
- Makes `Variables` optional in `UseQueryResult` and `UseClientRequestResult` types.
=> Fix FetchData and UseQueryOptions typings

packages/graphql-hooks/src/GraphQLClient.js, packages/graphql-hooks/test/unit/GraphQLClient.test.js
This PR decouples `onError` custom error handler from `logErrors` flag to allow the use of a custom handler without the need to set `logErrors` flag to `true`.
This align the actual behaviour of the 2 options to what is documented in the `README`.
#337
=> Fix onerror not called

config/rollup.config.js, examples/create-react-app/package.json, examples/create-react-app/src/App.js, packages/graphql-hooks-memcache/rollup.config.js, packages/graphql-hooks-memcache/src/.babelrc.js
- Copies the babel config for rollup, same as `graphql-hooks`
- Adds a overrides parameter to the rollup config generator
- Add custom `externals` array for `graphql-hooks-memcache`
- Updated the `create-react-app` to run on IE11 + added memcache
Verified the CRA example via the following steps:
1. In the root of the repo run: `lerna run build`
1. `cd examples/create-react-app`
1. `npm run build`
1. `serve -s build`
1. Verify `localhost:5000` on browserstack (IE11 and Edge)
#331
=> fix: graphql-hooks-memcache IE11 support

packages/graphql-hooks/index.d.ts
This fixes a breaking change introduced in 4.4.0 in #425.
#425 made the type `UseClientRequestResult` (and other functions) require a second type argument: `TGraphQLError`. To avoid a breaking change in a minor release, it should default to `object` if the user don't want to provide a specific `TGraphQLError` type upfront.
=> Make TGraphQLError default to "object"

packages/graphql-hooks/index.d.ts, packages/graphql-hooks/package.json, packages/graphql-hooks/src/GraphQLClient.js
- Fixes missing `useGETForQueries: boolean` in the TS typings for the `GraphQLClient` constructor.
- Fix missing `subscriptionClient` in the `GraphQLClient` constructor.
- Throws an error if trying to use `subscriptionClient` internally in `GraphQLClient` if it's not set.
=> Add useGETForQueries to TS typings for client constructor

.gitignore, README.md, packages/graphql-hooks/index.d.ts, packages/graphql-hooks/src/useClientRequest.js, packages/graphql-hooks/src/useQuery.js, packages/graphql-hooks/src/useSubscription.js, packages/graphql-hooks/test/unit/useClientRequest.test.js, packages/graphql-hooks/test/unit/useQuery.test.js
Allows passing a `GraphqlClient` to `useQuery`, `useSubscription`, and `useMutation`. It overrides any `ClientContext`.
Fixes #374
=> Add ability to pass client

packages/graphql-hooks/src/useClientRequest.js, packages/graphql-hooks/test/unit/useClientRequest.test.js, packages/graphql-hooks/test/unit/useQuery.test.js
Once we go into the loading state we can check if the previous state includes any error, if so we reset it to the initial state.
Solves https://github.com/nearform/graphql-hooks/issues/313
=> fix: clear errors on refetch via loading action

packages/graphql-hooks-memcache/package.json, packages/graphql-hooks-memcache/src/fnv1a.js, packages/graphql-hooks-memcache/src/index.js, packages/graphql-hooks-memcache/test/fnv1a.test.js
This PR fix [issue 496](https://github.com/nearform/graphql-hooks/issues/496) which supports Safari
=> fix(deps): fnv1a included which supports Safari

packages/graphql-hooks/index.d.ts, packages/graphql-hooks/src/useClientRequest.js, packages/graphql-hooks/test/unit/useClientRequest.test.js
This PR introduces the ability to trigger a reset. See [Issue #494](https://github.com/nearform/graphql-hooks/issues/494)
=> feat: adding reset function after useMutation

packages/graphql-hooks/src/useClientRequest.js, packages/graphql-hooks/test/unit/useClientRequest.test.js
It is the same idea behind https://github.com/nearform/graphql-hooks/pull/478
The unit test for this scenario is included
Related to [Issue #434](https://github.com/nearform/graphql-hooks/issues/434)
=> fix: including error when cached in SSR

packages/graphql-hooks/index.d.ts
Right now useSubscription callback uses `Result` type which has `error` and `data` fields.
But in reality callback will called with `{ data, errors }`. This PR fixes type mismatch. Also, I've added generics for Response and Variables similar to useQuery and useMutation.
Also includes changes from https://github.com/nearform/graphql-hooks/pull/504/ and solves https://github.com/nearform/graphql-hooks/issues/491
In future maybe it's better to convert subscription result to `{ data, error }` format? It'll be breaking change. Also, errors are not handled by `onError` method of `GraphQLClient`
=> fix: correct types for useSubscription

packages/graphql-hooks-memcache/src/index.js, packages/graphql-hooks-memcache/test/index.test.js
- Adds a `debug` option to memCache, disabled by default. When enabled, a second cache is created to allow retrieval of the original key from the hashed representation.
- Adds `rawGet` and `rawToKey` functions to memCache for retrieving values and original keys using hashed keys i.e. those returned by `.keys()`. The `rawToKey` function can only be used when `debug` is specified on the cache, otherwise it will throw an error.
https://github.com/nearform/graphql-hooks/issues/327
=> feat: added debug cache, rawToKey, and rawGet functions to memcache

.github/workflows/create-react-app-server.yml, examples/create-react-app/Dockerfile, examples/create-react-app/package.json, examples/create-react-app/server/db.js, package.json
Adds a mock graphql server to replace graph.cool (since that service is deprecated).
Server is needed to run the `create-react-app` example, but also to run acceptance test.
=> Add mock GraphQL server

examples/create-react-app/src/App.js, examples/create-react-app/src/components/CreatePost.js, examples/create-react-app/src/components/Posts.js, examples/typescript/src/App.tsx
Fixes the urls to the mock graphql server (previously graphcool, which is deprecated).
And makes acceptance test work again
=> Replace mock server calls

packages/graphql-hooks/index.d.ts
The `useQuery` is returning `undefined` for `data` on the first render, but this is not reflected in the typescript types. This PR changes the type to optional.
Although there is a suggestion #517 (and a PR #521) to change the `data` to always be an empty object, this would not be preferred, because that would cause a re-render.
- #517 
- #444
=> fix: response data is optional

examples/typescript/package.json, renovate.json
Reduces Renovate noise by:
- automerging all dependency types
- avoid creating PRs for the bumps which pass CI checks so that no notifications are sent
- label Renovate PRs with a "renovate" label
It also unpins dependencies where they were pinned.
=> chore: reduce renovate noise

packages/graphql-hooks-memcache/src/fnv1a.js, packages/graphql-hooks-memcache/test/fnv1a.test.js
Removes support for Buffer in the imported fnv1a library as we don't use it and because it causes issues when Buffer is not polyfilled, which happens by default in Webpack 5.
Fixes #608
=> fix: remove Buffer support from fnv1a

packages/graphql-hooks/index.d.ts
The exports 2 interfaces so they can be used externally, the reason for doing this is because i am working on a plugin for [graphql-code-generator](https://www.graphql-code-generator.com/) to generate typescript functions with graphql-hooks based on graphql queries
=> feat(typing): Export RequestOptions interface

packages/graphql-hooks/index.d.ts
The `Operation` interface currently defines the `variables` field as simply `object`, providing no type safety for variables. This PR adds the possibility to override this typing by means of a generic type param `TVariables`. The `GraphQLClient.request` and `GraphQLClient.getFetchOptions` methods are also extended with a Variables generic type param. The defaults have been set as `object` to ensure backwards compatibility with existing code.
None.
=> feat(typing): make Operation generic to be able to type variables

packages/graphql-hooks/package-lock.json, packages/graphql-hooks/package.json, packages/graphql-hooks/test/unit/GraphQLClient.test.js
`jsdom` is missing `TextEncoder` which is used in `formdata-node` invoked by the test suite. This PR adds `TextEncoder` to the `globals` object (as expected in a Node/Web environment)
https://github.com/nearform/graphql-hooks/runs/3159211453?check_suite_focus=true
=> build: fix ci build

README.md, jest.config.js, packages/graphql-hooks/index.d.ts, packages/graphql-hooks/src/useQuery.js, packages/graphql-hooks/test/setup.js, packages/graphql-hooks/test/setupAfterEnv.js, packages/graphql-hooks/test/unit/GraphQLClient.test.js, packages/graphql-hooks/test/unit/useClientRequest.test.js, packages/graphql-hooks/test/unit/useQuery.test.js
- Adds a  `skip` option to `useQuery` to offer the ability to skip a query conditionally
- The `skip` option is also watched for changes so the behavior of `useQuery` adapts to changing values of `skip`
- It also works with SSR
- It doesn't affect or change the `refetch` behavior in any way
Closes #154
=> feat: add ability to skip query entirely

examples/create-react-app/src/App.js, examples/create-react-app/src/components/CreatePost.js, examples/create-react-app/src/components/CreatePostForm.js, examples/create-react-app/src/components/ErrorBoundary.js, examples/create-react-app/src/components/Posts.js, examples/create-react-app/src/components/PostsWithErrorBoundary.js, examples/fastify-ssr/src/app/components/Hello.js, packages/graphql-hooks/src/useQuery.js, packages/graphql-hooks/test/integration/useQuery.test.js, packages/graphql-hooks/test/unit/useClientRequest.test.js, packages/graphql-hooks/test/unit/useQuery.test.js, packages/graphql-hooks/test/unit/useSubscription.test.js
Adds a `throwErrors` option to `useQuery` which throws errors instead of returning an `error` property in the resulting object.
This allows using Error Boundaries to intercept and display errors.
Resolves #324 
See the updated create-react-app example application
=> feat: throwErrors option in useQuery

packages/graphql-hooks/index.d.ts
`updateData` option receives `any, any` right now, it should be the `ResponseData` type provided to `useQuery<ResponseData>(...)`
=> fix: types

examples/create-react-app/Dockerfile
Some actions failed in latest commits ([example](https://github.com/nearform/graphql-hooks/runs/3729760181?check_suite_focus=true))
Maybe some internal dependencies changed, but copying `package-lock.json` in `create-react-app` example Dockerfile fixed the issue.
=> Adds package-lock.json file in Dockerfile

packages/graphql-hooks/src/useSubscription.js, packages/graphql-hooks/test/unit/useSubscription.test.js
Instead of silently ignoring errors sent from the server, this PR makes `useSubscription` handle errors in the way documented (but previously unimplemented) in the readme:
https://github.com/nearform/graphql-hooks/blob/b7ff57d30fa9894162e7145bc5a5ad98e0561f0b/README.md#L427-L432
Fixes https://github.com/nearform/graphql-hooks/issues/682
=> fix: handle errors in useSubscription

README.md, examples/create-react-app/src/components/CreatePost.js, examples/create-react-app/src/components/CreatePostForm.js, examples/create-react-app/src/components/Posts.js, examples/typescript/src/App.tsx, packages/graphql-hooks/index.d.ts, packages/graphql-hooks/package-lock.json, packages/graphql-hooks/package.json, packages/graphql-hooks/src/GraphQLClient.js, packages/graphql-hooks/src/createRefetchMutationsMap.js, packages/graphql-hooks/src/useClientRequest.js, packages/graphql-hooks/src/useQuery.js, packages/graphql-hooks/test/unit/createRefetchMutationsMap.test.js, packages/graphql-hooks/test/unit/useClientRequest.test.js, packages/graphql-hooks/test/unit/useQuery.test.js
I read the following issues:
> "Add ability to update the cache after a mutation #52"
> Refetch queries with mutations subscription #74
They contain a proposal by @bmullan91 and jgoux that I liked, the n.3 about **refetchAfterMutations**.
Meaning that when using `useQuery` we can subscribe to a list of mutations that make the entire query refetch.
It also allows a `filter` property with a function that allows refetch only when it evaluates true.
Query below executes again when `UPDATE_USER_MUTATION` executes and contains `userId === 1` in its variables.
```js
useQuery(TEST_QUERY, {
refetchAfterMutations: [
{
mutation: UPDATE_USER_MUTATION,
filter: ({ userId }) => userId === 1
}
]
})
```
The above is achieved by adding an EventEmitter ([new events …
=> feat: refetch query when subscribed mutation executes

README.md
Removes Spectrum community badge and adds a new "Community" section in the README. 
~**Important**: **_Before merging this PR, GitHub Discussions need to be enabled in the Settings. Here is how to do it: https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-repository
Only users with "write access" to this repository can do this._**~
Update: GitHub Discussions are now enabled.
Closes #719
=> docs: Removed spectrum badge and added Community section in the readme

.all-contributorsrc, .github/workflows/create-react-app-server.yml, CONTRIBUTING.md, README.md, packages/graphql-hooks/index.d.ts, packages/graphql-hooks/src/GraphQLClient.js, packages/graphql-hooks/test/unit/GraphQLClient.test.js
It's an implementation **proposal** for this issue https://github.com/nearform/graphql-hooks/issues/729. The goal is to give the user access to all properties on the Fetch API `Response` object. In our case we're interested in the headers to get the assigned cache keys on SSR rendered apps. With this approach, the user can define in which properties he/she is interested and just those will be returned under the defined key on the response of `client.request()` calls.
https://github.com/nearform/graphql-hooks/issues/729
=> feat: added response proxy

packages/graphql-hooks/src/GraphQLClient.js, packages/graphql-hooks/test/unit/GraphQLClient.test.js
As for now, when `fetch` is not defined what you get is an `fetch is not defined` error
By reading the tests the intention was to provide a more clear error `GraphQLClient: fetch must be polyfilled or passed in new GraphQLClient({ fetch })`
This was not happening because there was an error in the existence check
With this change the expected behavoir should be restored
=> fix: corrects the fetch existence check

README.md, packages/graphql-hooks/index.d.ts, packages/graphql-hooks/src/GraphQLClient.js, packages/graphql-hooks/test/unit/useSubscription.test.js
Adds an option for lazily instantiate the subscription client in order to provide an easier support for ssr without introducing breaking changes.
closes https://github.com/nearform/graphql-hooks/issues/681
=> feat: subscriptionClient accepts now a factory function as value

.github/workflows/ci.yml, package.json, packages/graphql-hooks/package.json, packages/graphql-hooks/test-d/cache.test-d.ts, packages/graphql-hooks/test-d/client-options.test-d.ts, packages/graphql-hooks/test-d/client.test-d.ts, packages/graphql-hooks/test-d/hooks.test-d.ts, packages/graphql-hooks/test-d/operation.test-d.ts, packages/graphql-hooks/test-d/subscription.test-d.ts
Add [`tsd`](https://github.com/SamVerschueren/tsd/) tests to `index.d.ts` file of the `graphql-hooks` package.
Also, adds a new CI run for the type tests.
Closes #741
#741
=> feat: add tsd tests

packages/graphql-hooks/index.d.ts, packages/graphql-hooks/src/GraphQLClient.js
Fixes a TypeScript issue when using the `persisted` option on the `useQuery` hook. In addition we'd like to reuse the already calculated `fetchOptions` instead of recalculate them again.
`no issue open`
=> fix: adjusted typing

.eslintrc.js, package.json
This PR should bump the version of eslint to 8.7.0.
There is a related PR #765
- [ X ] I have checked the [contributing document](../blob/master/CONTRIBUTING.md)
- [ - ] I have added or updated any relevant documentation
- [ - ] I have added or updated any relevant tests
=> chore: bump eslint version

packages/graphql-hooks/src/useClientRequest.js, packages/graphql-hooks/test/unit/useClientRequest.test.js
useClientRequests's fetchData no longer returns undefined when the hook is unmounted,
instead returns a result object with a descriptive error
It resolves #772 by returning a result object conforming to the typing and normal behavior of useClientRequest's fetchData
#772
=> feat(fetchData): no undefined when unmounted

packages/graphql-hooks/src/useClientRequest.js, packages/graphql-hooks/test/unit/useClientRequest.test.js
This PR avoids the overwrite of the cache if in SSR mode. In SSR mode the cache is already saved during fetchData execution. There is also a useEffect that is saving the cache after the store updates have finished. 
A test for useClientRequest did not wrap a call in act and so the useEffect was not being run in the test. Once the test was updated the test started failing.
Closes https://github.com/nearform/graphql-hooks/issues/68
- [Y] I have checked the [contributing document](../blob/master/CONTRIBUTING.md)
- [Y] I have added or updated any relevant documentation
- [Y] I have added or updated any relevant tests
=> fix:dont overwrite the cache for ssrMode

packages/graphql-hooks/index.d.ts
This PR adds `cacheKey` to UseClientRequestResult type
This goal is to be able to access to the `cacheKey` value of the `useQuery` result in Typescript projects.
I'm using it to manually invalidate the cache.
=> feat(typescript): adds cacheKey to UseClientRequestResult type

packages/graphql-hooks/src/GraphQLClient.ts
Updates fetch binding, fixes `[Fetch TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation]` error
Fixes #821
=> fix: update fetch bind

examples/typescript/package-lock.json
Updates the dependencies in the typescript example to mitigate hoisted dependencies causing problems. With these changes, running a full build from the point after `npm clean` will no longer produce an error.
Closes https://github.com/nearform/graphql-hooks/issues/735
=> Upgrade Typescript Example Dependencies

packages/graphql-hooks/src/types/common-types.ts, packages/graphql-hooks/src/useClientRequest.ts, packages/graphql-hooks/test-jsdom/unit/useClientRequest.test.tsx, packages/graphql-hooks/test-jsdom/unit/useQuery.test.tsx
The initial value of the `loading` flag should be false when `skip` option is true
Fixes #860
=> fix: set loading to false when skip is true

README.md, packages/graphql-hooks/src/GraphQLClient.ts, packages/graphql-hooks/test-node/GraphQLClient.test.ts
This PR will enable the setQueryData and invalidateQuery functions to receive operation object when being called.
Backward compatibility is met because we have changed the definition of these functions.
Closes: #930
=> fix: 930: use operation object in setQueryData

packages/graphql-hooks/src/useClientRequest.ts, packages/graphql-hooks/test-jsdom/integration/useManualQuery.test.tsx
This PR fixes #949 bug. To do that, it adds a check in the `useClientRequest` reducer not to reset the state if we are loading data.
It also adds a new integration test file for `useManualQuery`, it contains the same tests defined in `useQuery` plus new ones to keep track of this bug (the ones inside the "_useManualQuery with nested components_" describe block).
#949
=> fix: useManualQuery queryFn drilled to child component and invoked on mount does not toggle loading boolean

README.md
This PR improves the "Testing and mocking" section of the `README` providing a better description and example of how to mock an existing query using `LocalGraphQLClient`.
This PR closes #955
=> docs: update the README to better describe how to mock query data

packages/graphql-hooks/src/types/common-types.ts
The type for RefetchAfterMutationsData should allow an array with a mixture of `string`s and `RefetchAfterMutationItem`s, not just an array of one or an array of the other. This makes the array part include a union of those types.
This PR fixes the type for RefetchAfterMutationsData.
Fixes #984
=> Fix RefetchAfterMutationsData type's array part (#984)

packages/graphql-hooks/src/types/common-types.ts
With `object` as the type, it's cumbersome to type it correctly (can't pass a type parameter, can't just index on it, have to use a typecast in the function body). This commit makes it so we just use any as the variables type, as that is actually more what we want. From our perspective, we pass `filter` a parameter and want a boolean back.
Changes the type for the param to RefetchAfterMutationItem["filter"] to `any` so it can be used without doing a type cast in the function body.
Fixes #986
=> Use `any` for RefetchAfterMutationItem filter param (#986)

README.md, packages/graphql-hooks/src/createRefetchMutationsMap.js, packages/graphql-hooks/src/types/common-types.ts, packages/graphql-hooks/src/useQuery.ts, packages/graphql-hooks/test-jsdom/unit/createRefetchMutationsMap.test.ts, packages/graphql-hooks/test-jsdom/unit/useQuery.test.tsx
With this PR, a query is refetched only if the relative mutation (linked using `refetchAfterMutation` option) is successful.
I also renamed `conditionalRefetch` to `afterConditionsCheckRefetch` since it's not only a conditional refetch anymore, it also check for errors.
Introduced `refetchAfterMutations` as an optional parameter in [RefetchAfterMutationItem](https://github.com/nearform/graphql-hooks/pull/993/files#diff-d1d76b2c9ec609544e715dedb4b77efe053d6798016eeebc562a64dd3765cc79R187) type to determine whether or not to refetch the query if the mutation fails.
It resolves #988.
=> feat: refetch a query only if mutation doesn't fail (refetchAfterMutation option)

packages/graphql-hooks-memcache/package.json, packages/graphql-hooks/package.json
This PR does not ship any `src` directories, to prevent TS files parsing errors. It resolves #991 since we don't have any reproducible example.
#991
=> fix: removed src folder from graphql-hooks and graphql-hooks-memcache package.json files entry

packages/graphql-hooks/src/GraphQLClient.ts, packages/graphql-hooks/src/LocalGraphQLClient.ts, packages/graphql-hooks/src/LocalGraphQLError.ts, packages/graphql-hooks/src/middlewares/apqMiddleware.ts, packages/graphql-hooks/src/types/common-types.ts, packages/graphql-hooks/src/useQuery.ts
Ensures the `TGraphQLError` type is used in the `APIError` generic interface, allowing lib users to change the `graphQLErrors` property type if needed.
This change **should not** break compatibility with previous releases or any change visible to the end user. The `typescript-example` app ran fine with the libs compiled after changes.
I don't believe new documentation or tests are relevant for these changes.
closes https://github.com/nearform/graphql-hooks/issues/973
=> chore: ensure generic error type is used in apierror interface

packages/graphql-hooks/src/useClientRequest.ts, packages/graphql-hooks/test-jsdom/unit/useClientRequest.test.tsx
Closes: #1007 
For some reasons the `.off` function was not part of the event emitter in the authors environment, before putting the PR out of WIP need more details from the ticket author, to verify this was the actual problem.
=> fix: #1007 client.mutationsEmmiter.off is not a function

README.md, packages/graphql-hooks/src/LocalGraphQLClient.ts, packages/graphql-hooks/test-jsdom/unit/LocalGraphQLClient.test.tsx
Adds the ability to mock partial error responses when using `LocalGraphQLClient` by checking the mock response object for keys containing `Error` objects and collecting those errors into the returned error field 
Closes #1088
=> feat: add partial error response mocking

packages/graphql-hooks/src/useClientRequest.ts, packages/graphql-hooks/test-jsdom/unit/useClientRequest.test.tsx
Am try to do Optimistic Updates, after some mutations. What happens is after I do the mutations and I call `setQueryData`, for the first time it works, but subsequent calls to `setQueryData`, do not seem to work. 
From the source code I have seen DATA_UPDATED event is being handle by CACHE_HIT reducer, which updates the state conditionally (Am not sure even why the first call to `setQueryData` works because this condition is never meet when DATA_UPDATE event is fired).
So what I have just done is added another reducer that will handle DATA_UPDATED  and it always update the state data
Related issues
Closes https://github.com/nearform/graphql-hooks/issues/1065
=> fix: setQueryData not updating the UI

config/rollup.config.js, package.json, packages/graphql-hooks-memcache/rollup.config.js, packages/graphql-hooks/rollup.config.js
We were still using a lot of deprecated rollup plugins. This MR updates the references to the affected plugins. This also fixes some issues we were seeing with builds failing. 
Resolves #1146
=> chore: update rollup plugin packages

packages/graphql-hooks/package.json
- correct the release version of the graphql-hooks lib 
Closes #1153
=> chore: correct graphql-hooks release version

lerna.json, package.json
Bumps lerna from 7.4.2 to 8.1.2
[Dependabot change](https://github.com/nearform/graphql-hooks/pull/1162)
@all-contributors please add @edge33 for maintenance
=> chore(deps-dev): bump lerna from 7.4.2 to 8.1.2

examples/typescript/src/gql/fragment-masking.ts, packages/graphql-hooks/package.json, packages/graphql-hooks/src/createRefetchMutationsMap.ts, packages/graphql-hooks/src/types/typedDocumentNode.ts, packages/graphql-hooks/src/useClientRequest.ts, packages/graphql-hooks/src/useManualQuery.ts, packages/graphql-hooks/src/useMutation.ts, packages/graphql-hooks/src/useQuery.ts, packages/graphql-hooks/src/utils.ts
Removed the peer dependency graphql
Added dependency on @0no-co/graphql.web
Moved typedDocumentNode to inside project (dependency on DocumentNode which is imported fromno-co/graphqlinstead of graphql
closes https://github.com/nearform/graphql-hooks/issues/1177
=> fix: removed dependency on graphQL

packages/graphql-hooks/src/useQuery.ts, packages/graphql-hooks/test-jsdom/unit/useQuery.test.tsx
Client's own options can be changed by a middleware which makes useQuery repeat the call
It excludes client from comparison with a previous value in order to make a decision if a re-fetch is needed. Example: a middleware applies additional headers for specific queries only and restores them back to initial set after the request is complete. This runs `useEffect` hook again and it becomes an infinite loop.
none
=> feat!: exclude client mutations from refetch condition

README.md
Updated readMe with correct size from bundlephobia
https://bundlephobia.com/package/graphql-hooks@8.0.0
closes #1194
=> docs: updated readMe with correct bundle size

packages/graphql-hooks/src/GraphQLClient.ts, packages/graphql-hooks/test-jsdom/unit/GraphQLClient.test.ts
If a responseReducer was used respond with the result, even if falsy.
https://github.com/nearform/graphql-hooks/issues/1185
=> fix: return response reducer even if falsy

packages/graphql-hooks/package.json
Resolves a peer dependency error when installing the `graphql-hooks` package in a React 19.x project.
Fixes #1217
=> Adding React 19.x to peerDependencies

README.md, packages/graphql-hooks/src/useSubscription.ts, packages/graphql-hooks/test-jsdom/unit/useSubscription.test.tsx
Add skip option for subscriptions, making the creation of subscription conditional.
Closes #1225
=> feat: skip option for subscription
